### ISSUE TITLE
全局反馈

### ISSUE THREAD

**Issue by Abel-Liu** [openobj/openobj-web#5]

**Comment by Abel-Liu** [comment]
- 登录、注册改为按钮 

![1](https://cloud.githubusercontent.com/assets/7625589/14319384/9166c49e-fc43-11e5-9050-478bc56cd843.jpg)

- 顶部bar有点突兀；还有不同页面不需要这个bar

![2](https://cloud.githubusercontent.com/assets/7625589/14319436/c52e3668-fc43-11e5-9dc9-55177e56c1e7.jpg)

**Comment by alisawyj** [comment]
可以背景放一个大图，把登录、注册都放在右边
